
### cek api discord
GET https://discord.com/api/v10
Authorization: Bot token_authorization

### cek info user
GET https://discord.com/api/v10/users/@me
Authorization: Bot token_authorization

### check pesan dari berdasarkan chanel
GET https://discord.com/api/v10/channels/{channel_id}/messages
Authorization: Bot token_authorization